njt_pos: basics.o sqlite3.o
	gcc -o njt_pos -O3 -lsqlite3 basics.o
#sqlite3.o: sqlite3.c
#	gcc -Os -c -o sqlite3.o -DSQLITE_THREADSAFE=0 -DSQLITE_OMIT_LOAD_EXTENSION -DSQLITE_TEMP_STORE=2 sqlite3.c
basics.o: basics.c
	gcc -O3 -c -std=c99 -o basics.o basics.c
clean:
	rm -rf njt_pos basics.o sqlite3.o
